### PR TITLE
feat!: update site architecture with new Trivet features

### LINKED ISSUE #650: Sass/CSS styling syntax error
## Describe the bug

There is a syntax error with in [line #528 of _nav.scss](https://github.com/inclusive-design/idrc/blob/edb4b9068328fcb8057e8a11a4fbee1d98cb5d25/src/assets/styles/components/_nav.scss#L528).

It says:

```sass
text-decoration-color: var(currentColor, var(--black));
```

However, the first argument to `var` must be a property name.

It's likely that this should have been 

```sass
text-decoration-color: currentColor;
```

or maybe

```sass
text-decoration-color: var(--fl-fgColor, var(--black));
```

We'll need to review the styles to determine what the correct value should be.

## Expected behavior

There shouldn't be any syntax errors in the styles.

## Additional context

This was found while testing out https://github.com/fluid-project/eleventy-plugin-fluid/pull/168. It includes a new Sass and CSS processor; which caught this error.

### LINKED ISSUE #660: Use eleventy-plugin-fluid for asset processing

### LINKED ISSUE #661: Add site map

### LINKED ISSUE #662: Add news and views RSS feed

### LINKED ISSUE #663: Update linting based on Trivet

### LINKED ISSUE #664: Update Markdown config using eleventy-plugin-fluid conventions

### PR DESCRIPTION
**Pull request by greatislander**
* [x] This pull request has been tested by running `npm run test` without errors
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

Resolves #650, resolves #660, resolves #661, resolves #662, resolves #663, resolves #664.

## Steps to test

Build site, verify that it functions as expected with reference to the current release.

## Additional information

https://github.com/fluid-project/trivet/pull/337

## Related issues

Resolves #650, resolves #660, resolves #661, resolves #662, resolves #663, resolves #664.

### CODE REVIEW

**Comment by chosww** [comment]
Hey @greatislander, content of the project page is missing, and when I try to modify the content locally, I don't see the changes. I will continue investigate and let you know if I find what's causing this issue.

**Comment by chosww** [comment]
Sitemap doesn't look right format to me, when I navigated to /sitemap.xml

**Comment by chosww** [comment]
> Hey @greatislander, content of the projects page is missing, and when I try to modify the content locally, I don't see the changes. I will continue investigate and let you know if I find what's causing this issue.

I think it's structural issue caused by localization. I have a question about build result; I see that a directory named fr is present in current build, and it has subdirectory of projects. Shouldn't proper build create fr and en directories inside of projects?

**Comment by greatislander** [comment]
@chosww Take a look in `eleventy-plugin-fluid`, specifically the `generatePermalink` helper. The default behaviour is that the default language doesn't have a language slug at the start of the URL. So the English URL would be `/projects`, French would be `/fr/projets`.

**Comment by greatislander** [comment]
I'll look at the bug tomorrow.

**Comment by greatislander** [comment]
> Hey @greatislander, content of the projects page is missing, and when I try to modify the content locally, I don't see the changes. I will continue investigate and let you know if I find what's causing this issue.

Resoved in d6606ef! I had forgotten to account for a change to the JSON structure in `src/_data/config.json`.

**Comment by greatislander** [comment]
> Sitemap doesn't look right format to me, when I navigated to /sitemap.xml

Can you give me some more details about what you are expecting?

**Pull request merged**
