### PR TITLE
feat: update consulting page layout (resolves #65)

### LINKED ISSUE #65: Update the IDRC consulting page
Vera contacted me about adding some information to the IDRC consulting page. I've updated them in the figma screens. Key updates include - one h2 on the page with "our services", with h3's being the services themselves (auditing, training, and consulting). Also, there's 2 points of contact on this page now - Vera for consulting and training, Lisa for auditing.

DK: https://www.figma.com/file/i9bmZQt8dXqHcmbTgzmu0l/IDRCWebsite_Screens_2020?node-id=2%3A2794
MB: https://www.figma.com/file/i9bmZQt8dXqHcmbTgzmu0l/IDRCWebsite_Screens_2020?node-id=2%3A924

### PR DESCRIPTION
**Pull request by greatislander**
* [x] This pull request has been tested by running `npm run test` without errors
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

This PR updates the layout of the consulting page as requested.

TODO:

- [x] Vertical spacing before/after headings on mobile

## Steps to test

1. Visit https://deploy-preview-88--idrc.netlify.app/consulting.

**Expected behavior:** New page layout matches expectations.

## Additional information

Subsections can now be created based on either `<h3>` or `<h4>` elements based on a setting in the parent section. This allows the customized column division requested for the consulting page.

## Related issues

Resolves #65.

### CODE REVIEW

**Comment by cherylhjli** [comment]
Updated padding for desktop and mobile here: https://www.figma.com/file/i9bmZQt8dXqHcmbTgzmu0l/IDRCWebsite_Screens_2020?node-id=681%3A590

**Comment by cherylhjli** [comment]
hey! it looks good. Could we reduce the spacing between body > h2 by half, and h2 > body by just a smidge, maybe by 1/4 or 1/5?

**Comment by greatislander** [comment]
> hey! it looks good. Could we reduce the spacing between body > h2 by half, and h2 > body by just a smidge, maybe by 1/4 or 1/5?

Done, @cherylhjli

**Comment by cherylhjli** [comment]
For some reason I'm not seeing the changes? The space between body and h2 still look too big.

**Comment by cherylhjli** [comment]
Screen Shot 2020-09-20 at 1 53 36 PM

**Comment by cherylhjli** [comment]
IDRC-Consulting-Inclusive-Design-Research-Centre

**Comment by cherylhjli** [comment]
Looks great! Only thing I noticed is on mobile, there's a giant gap here:
Screen Shot 2020-09-22 at 2 54 34 PM

Can we make that space the same height as between the ILDH body copy and "services we offer"?
Screen Shot 2020-09-22 at 2 54 53 PM

**Comment by greatislander** [comment]
@cherylhjli Fixed in the latest commit, check the deploy preview when it is updated?

**Review by cherylhjli — APPROVED** [review]

**Pull request merged**
