### PR TITLE
feat: minimal team page (resolves #55)

### LINKED ISSUE #55: Add About Us / Team (round one)
[Figma designs](https://www.figma.com/file/i9bmZQt8dXqHcmbTgzmu0l/IDRCWebsite_Screens_2020?node-id=89%3A1198).

### PR DESCRIPTION
**Pull request by greatislander**
* [x] This pull request has been tested by running `npm run test` without errors
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

Adds minimal implementation of a team page. Individual team member pages are created but not linked from the team page and not styled yet.

TODO:

- [x] Add people to CMS for editing.

## Steps to test

1. Visit deploy preview.
2. Review _About / Team_ page.

**Expected behavior:** Matches designs.

## Additional information

Not applicable.

## Related issues

Resolves #55.

### CODE REVIEW

**Comment by cherylhjli** [comment]
The padding looks a little off :) Let's add some?
Screen Shot 2020-08-27 at 3 16 11 PM
Screen Shot 2020-08-27 at 3 16 00 PM

**Comment by greatislander** [comment]
Oops! Fixed now.

**Comment by cherylhjli** [comment]
it seems to be fixed on firefox, not on chrome :(

firefox also shows this:

Screen Shot 2020-08-27 at 3 31 00 PM

**Comment by greatislander** [comment]
@cherylhjli check again :)

**Comment by cherylhjli** [comment]
Still got that funky staircase thing going on! Only on tablet view though.

**Comment by greatislander** [comment]
@cherylhjli Argh. I think I've got it this time. (Needs to deploy.)

**Pull request merged**
