### PR TITLE
GH-465: Add CMS editor components (resolves #464, #465, #466)

### LINKED ISSUE #464: CMS: Allow images added to content to be positioned and resized using different options
## Is your feature request related to a problem? Please describe.

Currently the user has no control over the positioning and scaling of images added to the content. This causes users to adopt work-arounds to get the positioning and scaling they desire as mentioned in #453 .

## Describe the solution you'd like

When adding images (or any other media), there should be options for:
* Position: left, centre, right
* Scale: Percentage values 25%, 50%, 75%, 100%.

Possibly also:
* Max height value in pixels - for situations where the image scale causes an image to stretch vertically too much.

## Additional context

WeCount has some additional options for image positioning and scaling. Could be worth implementing something similar.

### PR DESCRIPTION
**Pull request by cindyli**
* [X] This pull request has been tested by running `npm run test` without errors
* [X] This pull request has been built by running `npm run build` without errors
* [X] This isn't a duplicate of an existing pull request

## Description

1. Add three Netlify CMS editor components: YouTube embed, Image and Text, Image Position
2. As Eleventy shortcodes generated by these components are only parsed for the "body" field in the markdown data file. These components are only made available in editors for body fields.

Note that as discussed with Vera and David, the preview for these components in the CMS authoring interface is not implemented.

## Steps to test

1. Go to /admin page to author;
2. Click any collection that has a "body" field such as "Page"; Click a data entry and scroll to the "body" field;
3. Click the "+" icon on the editor menu. These three new features should be listed;
4.  Test each feature.

**Expected behavior:** 
These features should work as described in tickets.

### CODE REVIEW

**Comment by jhung** [comment]
@cindyli I'm not done testing, but I discovered that it's possible to insert Images and Text or Youtube components into the content of an Image + Text block.

To reproduce:
1. Insert an Image & Text block.
2. In the Content field of the Image & Text block, add a Youtube or another Image and Text component.

While this can create some interesting layouts (i.e. you can effectively put an image and a Youtube video side by side), I think it could cause some confusion.

What are your thoughts?

**Comment by cindyli** [comment]
> While this can create some interesting layouts (i.e. you can effectively put an image and a Youtube video side by side), I think it could cause some confusion.

Your concern makes sense. I've removed the editor components menu item from the Content field of Image and Text component.

**Comment by jhung** [comment]
Would it be possible to only have one Image component which has Image Position, Scale, Max Height, Optional text content, and vertical alignment? This way users only need to deal with a single image component instead of 3.

**Comment by cindyli** [comment]
> Would it be possible to only have one Image component which has Image Position, Scale, Max Height, Optional text content, and vertical alignment? This way users only need to deal with a single image component instead of 3.

Yes, it's possible. I'll make the change.

**Comment by cindyli** [comment]
@jhung Now there's a editor component called "Image Position with Text" that combines features from "Image and Text" and "Image Position". "Image and Text" and "Image Position" components have been removed.

As now there are quite a number of options when using "Image Position with Text". I wrote hints for some options to explain when they should be used. Please let me know if hints are unclear.

Moreover, I suggest to keep the built-in "Image" component for the markdown editor. This component wrote straight markdown syntax into the data file, which can be parsed and showed correctly everywhere. This is especially useful for non-body fields where the eleventy shortcodes written by "Image Position with Text" are not parsed.

This pull request is ready for another look.

**Comment by jhung** [comment]
@cindyli "Optional" appears twice in the text field labels for Content and Vertical Alignment

image

What happens in the situation where the user has aligned the image center and has entered text into the Content? Would it appear centred below? Would vertical alignment be ignored in this case if specified?

**Comment by cindyli** [comment]
> "Optional" appears twice in the text field labels for Content and Vertical Alignment

Good catch. Fixed.

> What happens in the situation where the user has aligned the image center and has entered text into the Content? Would it appear centred below?
When the Content field has text and the user sets the image position to "Center", "Center" will be ignored and the position will be auto reset to "left". I added a hint under the "image position" field says: `The "center" choice applies to the image only case when the content is not provided. If the "center" is selected when the content is provided, the image position will be reset to "left"`.

> Would vertical alignment be ignored in this case if specified?
The vertical alignment only applies to cases that the Content is provided. The hint text under this field says: `Only select when the content is provided`.

**Review by jhung — APPROVED** [review]
I did some manual testing and it seems to work. Thanks!

**Pull request merged**
