### PR TITLE
fixed the size of h1 (resolves #40)

### LINKED ISSUE #40: H1 is larger in  whole website in mobile view (not readable)
## Describe the bug
The size of the h1 (Which is Inclusive Design Research Centre) is two large **not readable** in  mobile view ###the name changed to be small

## To Reproduce

1. Go to 'https://idrc.ocadu.ca/'
2. Click on 'on home page'
3. in mobile view'see the size of h1 is two large'

## Screenshots before--
idrc h1 issue

### after--
issue fixed h1

## Smartphone (please complete the following information):

- Device: [e.g. iPhone 5 ,5s ,6 ]
- Browser [e.g. stock browser]

## Additional context
i already fixed this issue for all the devices added just media query for this here the link of my pr #39 
@cindyli @greatislander @gtirloni

### PR DESCRIPTION
**Pull request by Raunaksingh100**
* [x] This pull request has been tested by running `npm run test` without errors
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description
Fixed the h1 in mobile view added the media query see in the screenshot for the better understanding

## here the preview link by (NETLIFY)--
https://deploy-preview-39--idrc.netlify.app/

## screenshot before--
idrc h1 issue

##after--
issue fixed h1

## issues

#40 FIXED
  @greatislander  @jhung plz review it

### CODE REVIEW

**Comment by Raunaksingh100** [comment]
@greatislander plz help me to fixed these pr and can you tell me how i run this project in my local with ""npm "" because i am new to open source contribution

**Comment by gtirloni** [comment]
Here are the steps to start the website on your local computer:

```
$ git clone https://github.com/inclusive-design/idrc
$ cd idrc
$ npm install
$ npm run start
```

After that, you can reach the website at [http://localhost:3000/](http://localhost:3000/)

Tested with Node.js 12.18.2

**Comment by Raunaksingh100** [comment]
@gtirloni  can you tell what is problem in my pr plz review it.......

**Comment by Raunaksingh100** [comment]
@gtirloni  plz review my PR and merged it and this works ...................
fixed

**Comment by gtirloni** [comment]
> @gtirloni plz review my PR

Hi @Raunaksingh100, thanks for this PR! I'm not really the best person to review frontend PR's so I'll defer to @greatislander. He might not be available this week though. Stay tuned and thanks again!

**Comment by Raunaksingh100** [comment]
@gtirloni i am facing this problem now while iam commiting if you have the group of this orgainsar=tion on GITTER plz share the link..
error in idrc

**Comment by Raunaksingh100** [comment]
hi i am facing this problem i dont know why see in he screenshot for the better understanding
error in idrc

**Comment by Raunaksingh100** [comment]
@cindyli @gtirloni i FIXED the error now plz revire my PR

**Comment by jobara** [comment]
@cherylhjli, @greatislander and @jhung are one of you able to review this PR?

**Comment by greatislander** [comment]
Hi @Raunaksingh100, thank you for your contribution. @cherylhjli, who is leading ongoing design of the IDRC website as we continue to expand its features and functionality, will be developing a design system for the site which will include improvements to the typography (see our project planning page: https://github.com/inclusive-design/idrc/projects/2#card-42813694). Rather than merging this PR, I am going to await the results of that process and we will be sure to incorporate your feedback from #40 into the design work as we move forward.

**Pull request closed without merging**
