### PR TITLE
feat: add scatterplot graphic (resolves #4)

### LINKED ISSUE #4: Scatterplot graphic
Add scatter plot graphic to homepage.

### PR DESCRIPTION
**Pull request by greatislander**
* [x] This pull request has been tested by running `npm run test` without errors
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

Adds scatterplot graphic to home page "What is Inclusive Design?" section.

## Steps to test

1. Review deploy preview.

**Expected behavior:** Implementation matches designs.

## Additional information

Not applicable.

## Related issues

- Resolves #4.

### CODE REVIEW

**Comment by cherylhjli** [comment]
Not seeing it?

**Comment by greatislander** [comment]
@cherylhjli Fixed now.

**Comment by cherylhjli** [comment]
can you make it a wee bit more zoomed in? I think visually its nicer to have the different dots bleeding off the edges on all sides, if possible. Let me know if I can crop something up for this.

Screen Shot 2020-04-27 at 10 43 43 AM

**Comment by greatislander** [comment]
@cherylhjli Try now.

**Comment by cherylhjli** [comment]
A little bit more to the left, so its centred in its half of the screen?

**Comment by greatislander** [comment]
@cherylhjli updated.

**Pull request merged**
