### PR TITLE
GH-212: add thumbnail to projects and tools (Resolves #212)

### LINKED ISSUE #212: Have a way to include an image with a project on the IDRC site
There should be a way to optionally include a visual with each project in the Projects page. The image can be a logo or some other image.

## Describe the solution you'd like

In terms of structure, the image will appear after the project description and before the project link:
1. Project name
2. Project Title
3. Image
4. Link
5. Optional body content

Using CSS if possible (or image processing on build) the image should scale well on mobile and desktop. `max-width` and `max-height` will likely be required to ensure that images don't end up occupying too much space. 

From the CMS side, the author can upload an image into the project article similar to how a thumbnail image can be attached to an article in the Ideas section.

### PR DESCRIPTION
**Pull request by jobara**
* [ ] This pull request has been tested by running `npm run test` without errors
* [ ] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

Add the options for supplying thumbnails to the projects and tools page, similar to the ideas page.

## Steps to test

1. "projects and tools" page should load with thumbnails for some of the projects
2. going to the admin page, should show an option to add thumbnails to the projects and tools pages.

## Additional information

There is currently a build error that needs to be investigated that is preventing the site from being built.

`unknown block tag: getUrl` Related to generating the thumbnails. It's unclear why this doesn't work as the shortcode works on the ideas page.

## Related issues

Resolves #212

### CODE REVIEW

**Comment by jobara** [comment]
@greatislander when have some time, could you please take a look at this PR. I'm running into an issue with the `getUrl` shortcode not being recognized and causing a `unknown block tag: getUrl` error. However, this only happens in the `projects.njk` layout and woks fine in the `ideas.njk` layout.

**Comment by greatislander** [comment]
@jobara I remember running into this error before but I am not sure how I fixed it. I am wondering if the problem is the Sharp plugin— it hasn't been updated in 15 months and it might make sense to explore an alternative such as the official image plugin: https://www.11ty.dev/docs/plugins/image/

**Comment by jobara** [comment]
> @jobara I remember running into this error before but I am not sure how I fixed it. I am wondering if the problem is the Sharp plugin— it hasn't been updated in 15 months and it might make sense to explore an alternative such as the official image plugin: https://www.11ty.dev/docs/plugins/image/

I was looking at the eleventy-img plugin. One thing that it doesn't seem to allow is for fine configuration of resizing images. It looks like it will only resize the width, and preserve aspect ratio. [There doesn't appear to be any way to modify this configuration either](https://github.com/11ty/eleventy-img/blob/e009e566265694bab785508bf210296c5d19c116/img.js#L430-L438). From the [current use](https://github.com/inclusive-design/idrc/blob/a85354f51183d7f0916273ab24d051336a4888d5/src/_includes/layouts/ideas.njk#L20-L28) of the current sharp plugin, it looks like we're explicitly specifying the width and height and using the `fit` to have the image cropped to those dimensions.

**Comment by jobara** [comment]
Here's an issue that's file about that. https://github.com/11ty/eleventy-img/issues/31

**Comment by jobara** [comment]
@greatislander I've tracked down the issue to [precompile](https://github.com/inclusive-design/idrc/blob/a85354f51183d7f0916273ab24d051336a4888d5/src/admin/admin.11ty.js#L22) in admin.11ty.js.

**Comment by greatislander** [comment]
@jobara The precompile step is used to generate Nunjucks templates which are used for previews in the CMS.

**Comment by cindyli** [comment]
Resolved with https://github.com/inclusive-design/idrc/issues/426

**Pull request closed without merging**
