### PR TITLE
GH-166: Integrate UI Options (resolves #166)

### LINKED ISSUE #166: Integrate UI Options
## Is your feature request related to a problem? Please describe.

The IDRC is missing UI Options. It was noticed while showing the website, that UIO wasn't present.

## Describe the solution you'd like

Integrates UIO with the following features:

- UIO interface styles
- Adjuster: line spacing
- Adjuster: text style
- Adjuster: contrast themes
- Adjuster: enhance inputs
- Adjuster: syllables

## Additional context

The work was originally started as #112

### PR DESCRIPTION
**Pull request by jobara**
* [x] This pull request has been tested by running `npm run test` without errors
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

Integrates UI Options into the IDRC site

## Steps to test

1. Open the UIO (Show Preferences) tab
2. Change the preference and ensure that the site is updated to match the specified preferences
3. Repeat for each page.

## Additional information

Pay careful attention to the colours applied by the contrast themes for all of the pages.

## Related issues

Resolves #166

### CODE REVIEW

**Comment by jobara** [comment]
@greatislander This is ready for review. Although I need to update the Infusion dependency to an actual dev release once https://github.com/fluid-project/infusion/pull/1060 has been merged into Infusion's main.

Also I believe that the BackstopJS check failure is due to my PR coming from a fork. Forks only have read access from the GITHUB_TOKEN and as such cannot write. See: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token I also brought back the non-docker backstop run for CI.

**Review by greatislander — CHANGES_REQUESTED** [review]
While testing, I noticed that when a contrast theme is applied, links in primary menu dropdowns and in the About pages' secondary navigation disappear when they are both focused and active:

Screen Shot 2021-11-19 at 8 47 55 AM

Screen Shot 2021-11-19 at 8 48 23 AM

This happens in Safari, Firefox and Edge.

**Review by greatislander — CHANGES_REQUESTED** [review]
It looks like the primary navigation's menu items have a higher z-index than the UIO button, which cuts off its drop shadow.

Screen Shot 2021-11-19 at 8 52 54 AM

**Review by greatislander — CHANGES_REQUESTED** [review]
Related to the previous comment, I wonder if it might look cleaner to remove the bottom border from the prefs panel container and give it the same background as the page header of the current page. That would look something like this:

Screen Shot 2021-11-19 at 8 55 04 AM

**Comment by jobara** [comment]
Just remembered that I need to update to a proper dev release of infusion. I'll do that now.

**Comment by jobara** [comment]
@greatislander I've updated Infusion. Should be ready to review now.

**Review by greatislander — CHANGES_REQUESTED** [review]
There's still a few issues with active states for the banner/primary nav:

Brand, active, black on yellow:

Screen Shot 2021-12-06 at 9 09 06 AM

Brand, active, grey on white:

Screen Shot 2021-12-06 at 9 09 54 AM

Brand (home page), active, light grey on dark grey:

Screen Shot 2021-12-06 at 9 11 47 AM

**Review by greatislander — APPROVED** [review]

**Pull request merged**
